#ifndef MICROSWIM_CUSTOM_CONFIGURATION_H
#define MICROSWIM_CUSTOM_CONFIGURATION_H

#define PROTOCOL_PERIOD 1
#define PING_REQ_PERIOD 0.5
#define SUSPECT_TIMEOUT 20

#define MAXIMUM_MEMBERS_IN_AN_UPDATE 4
#define FAILURE_DETECTION_GROUP 3
#define GOSSIP_FANOUT 4

#define MAXIMUM_MEMBERS 8
#define MAXIMUM_UPDATES 8
#define MAXIMUM_PINGS 8
#define MAXIMUM_EVENTS 10

#define BUFFER_SIZE 2048

#endif
