#ifndef MICROSWIM_CONSTANTS_H
#define MICROSWIM_CONSTANTS_H

#define UUID_SIZE 37
// TODO: config.h.in file.
#define PROTOCOL_PERIOD 1
#define PING_REQ_PERIOD 0.5
#define SUSPECT_TIMEOUT 20

#define MAXIMUM_MEMBERS_IN_AN_UPDATE 4
#define FAILURE_DETECTION_GROUP 3
#define GOSSIP_FANOUT 4

#define MAXIMUM_MEMBERS 128
#define MAXIMUM_UPDATES 128
#define MAXIMUM_PINGS 128

#define BUFFER_SIZE 2048

// Masks
#define SIN_FAMILY 0x01
#define SIN_PORT 0x02
#define SIN_ADDR 0x04

#endif
