#ifndef MICROSWIM_CONSTANTS_H
#define MICROSWIM_CONSTANTS_H

#define UUID_SIZE 37

#define SIN_FAMILY 0x01
#define SIN_PORT 0x02
#define SIN_ADDR 0x04

#define CBOR_MAX_KEY_SIZE 16
#define MAXIMUM_URI_LENGTH 64

#endif
