#ifndef MICROSWIM_CONFIGURATION_H
#define MICROSWIM_CONFIGURATION_H

#define PROTOCOL_PERIOD 5
#define PING_REQ_PERIOD 2.5
#define SUSPECT_TIMEOUT 60

#define MAXIMUM_MEMBERS_IN_AN_UPDATE 3
#define FAILURE_DETECTION_GROUP 3
#define GOSSIP_FANOUT 1

#define MAXIMUM_MEMBERS 8
#define MAXIMUM_UPDATES 8
#define MAXIMUM_PINGS 8
#define MAXIMUM_EVENTS 10

#define BUFFER_SIZE 512

#endif
